name: build

on: [push, pull_request]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: Checkout qwc-docker
        uses: actions/checkout@master
        with:
          repository: qwc-services/qwc-docker
          path: qwc-docker

      - name: Start demo database
        run: |
          cd qwc-docker
          cp pg_service.conf ~/.pg_service.conf
          sed -i 's|host=qwc-postgis|host=localhost|g' ~/.pg_service.conf
          sed -i 's|port=5432|port=5439|g' ~/.pg_service.conf
          sed -Ei "s|^(\s*POSTGRES_PASSWORD:).*$|\1 'waej7WuoOoth0wor'|" docker-compose-example.yml
          docker compose -f docker-compose-example.yml up -d qwc-postgis qwc-config-db-migrate qwc-qgis-server

      - name: Setting up python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: Run unittests
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          PYTHONPATH=$PWD/src python3 test.py

    build:
      needs: test
      runs-on: ubuntu-latest
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      steps:

      - uses: actions/checkout@master

      - name: Get version tag
        id: get_tag
        run: |
          if [ ${{ endsWith(github.ref, '-lts') }} = true ]; then
            echo "tag=latest-lts,latest-${GITHUB_REF:11:4}-lts,${GITHUB_REF:10}" >>$GITHUB_OUTPUT
          else
            echo "tag=latest,${GITHUB_REF:10}" >>$GITHUB_OUTPUT
          fi

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: sourcepole/${{ github.event.repository.name }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ steps.get_tag.outputs.tag }}"
