name: build

on: [push, pull_request]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: Checkout qwc-docker
        uses: actions/checkout@master
        with:
          repository: qwc-services/qwc-docker
          path: qwc-docker

      - name: Start demo database
        run: |
          cd qwc-docker
          sed -i 's|host=qwc-postgis|host=localhost|g' pg_service-write.conf
          sed -i 's|port=5432|port=5439|g' pg_service-write.conf
          cp pg_service-write.conf ~/.pg_service.conf
          docker-compose -f docker-compose-example.yml up -d qwc-postgis

      - name: Setting up python 3.6
        uses: actions/setup-python@v2
        with:
            python-version: '3.6'

      - name: Run unittests
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python3 test.py

    build:
      needs: test
      runs-on: ubuntu-latest
      if: github.event_name == 'push'
      steps:

      - uses: actions/checkout@master

      - name: Get version tag
        id: get_tag
        run: |
          if [ ${{ startsWith(github.ref, 'refs/tags/') }} = true ]; then
            echo ::set-output name=tag::latest,${GITHUB_REF:10}
          else
            echo ::set-output name=tag::latest
          fi

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.18
        with:
          name: sourcepole/${{ github.event.repository.name }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ steps.get_tag.outputs.tag }}"
